### ISSUE TITLE
[Feature request]支援键盘方向键快进、倒退功能

### ISSUE THREAD

**Issue by TonyLin2K19** [MirrichWangD/kikoeru-express#1]
十分感谢您的作品
是目前我找到最好的kikoeru框架了
只是目前播放的时候步支援键盘快进、倒退
只能用滑鼠标去点
如果可以的话，希望能在未来的版本支援

**Comment by MirrichWangD** [comment]
感谢您的支持，后续更新版本我将解决这个问题！

Thanks for your subscribe, I will solve this issue in the next update!

**Comment by LittleMio** [comment]
@MirrichWangD 你好，感谢你能抽空阅读这条信息，我想建议未来能添加webdav的支持，以添加alist等网盘内的文件
非常感谢您的考虑，我也期待这一功能的实现

**Comment by MirrichWangD** [comment]
> @MirrichWangD 你好，感谢你能抽空阅读这条信息，我想建议未来能添加webdav的支持，以添加alist等网盘内的文件 非常感谢您的考虑，我也期待这一功能的实现

目前来说下一个版本计划是做一个内置AI翻译功能，这个功能我先标记一下后续有时间继续更新
